databases:
  - name: event watching_DB
    databaseName: event_watching_db
    user: event watching
    region: singapore

services:
  - type: web
    name: event watching
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: event watching_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
